[project]
name = "workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "pip-tools==7.4.1",
    "pip==24.3.1",
    "pipenv==2024.4.0",
    "pipx==1.7.1",
    "python3-openid==3.2.0",
]
